name: Sync GitLab master to GitHub main

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 设置 SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7999 gitlab.cern.ch >> ~/.ssh/known_hosts || true
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # 2️⃣ Clone GitLab
      - name: Clone GitLab
        run: |
          git clone -b master ssh://git@gitlab.cern.ch:7999/atlas-physics-office/HIGP/ANA-HIGP-2024-02/ANA-HIGP-2024-02-INT1.git repo
          cd repo
          # git config user.name "yong7"
          # git config user.email "yong.z@cern.ch"
          git remote add github git@github.com:yong7/ANA-HIGP-2024-02-INT1.git
          git push github master:main 
